version: 1.0.{build}
environment:
  TESTING_ON_AV: 1
  matrix:
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
install:
- cmd: pip install tox
build: off
test_script:
- cmd: tox
